version: '3'
services: 
    db:
      container_name: postgres_mybatis
      image: postgres:13
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=camunda
        - POSTGRES_USER=camunda
        - POSTGRES_PASSWORD=camunda
      volumes:
        - ./sql:/docker-entrypoint-initdb.d/:rw